project:
  name: jwt

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt
    username: my
    password: 123456789
    # hikaricp
    # The default value of mysql wait_timeout is 28800 (8 hours).
    # If it is burdensome to set wait_timeout directly in mysql, set it as a session in properties.
    hikari:
      connection-init-sql: set wait_timeout = 610
      max-lifetime: 600000
  # jpa
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

# server
server:
  port: 9090

# jwt
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  # time to live
  ttl:
    access-token: 60000 # 60 seconds
    refresh-token: 120000 # 120 seconds

# redis
redis:
  host: localhost
  port: 6379
  password: 123456789
